// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/zh1lu0/gocamp/internal/biz"
	"github.com/zh1lu0/gocamp/internal/conf"
	"github.com/zh1lu0/gocamp/internal/data"
	"github.com/zh1lu0/gocamp/internal/server"
	"github.com/zh1lu0/gocamp/internal/service"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData, logger)
	helloUsecase := biz.NewGreeterUsecase(helloRepo, logger)
	helloService := service.NewHelloService(helloUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, helloService, logger)
	grpcServer := server.NewGRPCServer(confServer, helloService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
